INSERT INTO CATEGORIES (name) VALUES ('MONITORS');
INSERT INTO CATEGORIES (name) VALUES ('LAPTOPS');
INSERT INTO CATEGORIES (name) VALUES ('DESKTOPS');
INSERT INTO CATEGORIES (name) VALUES ('HARD DISKS');